### ISSUE TITLE
Missing com.sebaslab.svelto.unsafe folder in Packages

### ISSUE THREAD

**Issue by Jlabarca** [sebas77/Svelto.MiniExamples#10]
Unity throws this error opening doofuses example
![image](https://user-images.githubusercontent.com/5511303/136725597-a8db1244-f344-49c9-b377-033b16dae5d1.png)

Why are those dependencies pushed in this repo ? 
and not included as: 
` "com.sebaslab.svelto.unsafe": "https://github.com/sebas77/com.sebaslab.svelto.unsafe.git"`

https://github.com/sebas77/Svelto.MiniExamples/blob/2cb85a9448c8b0ed0536b47f8efe1da5b8a3e97c/Example1-DOTS-DoofusesMustEat/DOOFUSES_UECS/Packages/manifest.json#L6

**Comment by sebas77** [comment]
The package should be in the package folder, but I see it's missing. I'll fix it asap

**Comment by sebas77** [comment]
fixed thank you
