### ISSUE TITLE
Multiplayer examples?

### ISSUE THREAD

**Issue by noncom** [sebas77/Svelto.MiniExamples#13]
It would be great to have at least a minimal multiplayer example with Svelto.ECS

I know that this might seem a bit beyond the scope, but:
- Organizing network sync of ECS-based worlds quite fundamentally depends on the ECS itself and its detailed workings. Much more so than in just a OOP game where networking is mainly a question of general architecture and patterns.
- Although networking might be seen as something platform/library-dependent, the important part is not the transport, but the most idiomatic way of syncing Svelto.ECS world between server and client.

**Comment by sebas77** [comment]
I have no plans to do this. DOTS net code may be a better option as it is supposed to work out of the box
