### ISSUE TITLE
An exception that prevents the DOOFUSES_DOTS example from working

### ISSUE THREAD

**Issue by noncom** [sebas77/Svelto.MiniExamples#14]
When trying to run the DOOFUSES_DOTS example I'm getting this exception

```csharp
ArgumentException: Unknown Type:`Svelto.ECS.SveltoOnDOTS.SyncSveltoToDOTSEngine` All ComponentType must be known at compile time. For generic components, each concrete type must be registered with [RegisterGenericComponentType].
Unity.Entities.TypeManager.ManagedException (System.Type type) (at ./Library/PackageCache/com.unity.entities@1.0.8/Unity.Entities/Types/TypeManager.cs:1706)
Unity.Entities.TypeManager.ManagedException[T] () (at ./Library/PackageCache/com.unity.entities@1.0.8/Unity.Entities/Types/TypeManager.cs:1687)
Unity.Entities.TypeManager.GetSystemTypeIndex[T] () (at ./Library/PackageCache/com.unity.entities@1.0.8/Unity.Entities/Types/TypeManagerSystems.cs:1005)
Unity.Entities.World.AddSystemManaged[T] (T system) (at ./Library/PackageCache/com.unity.entities@1.0.8/Unity.Entities/World.cs:930)
Svelto.ECS.SveltoOnDOTS.SveltoOnDOTSEnginesGroup.AddSveltoToDOTSSyncEngine (Svelto.ECS.SveltoOnDOTS.SyncSveltoToDOTSEngine engine) (at ./Packages/com.sebaslab.svelto.ecs/Extensions/Unity/DOTS/UECS/SveltoOnDOTSEnginesGroup.cs:75)
Svelto.ECS.MiniExamples.DoofusesDOTS.SveltoCompositionRoot.ComposeEnginesRoot () (at Assets/Code/SveltoCompositionRoot.cs:100)
UnityEngine.Debug:LogException(Exception)
Svelto.ECS.MiniExamples.DoofusesDOTS.<ComposeEnginesRoot>d__3:MoveNext() (at Assets/Code/SveltoCompositionRoot.cs:103)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(ValueTuple`5)
Svelto.ECS.MiniExamples.DoofusesDOTS.<LoadAssetAndCreatePrefabs>d__5:MoveNext() (at Assets/Code/SveltoCompositionRoot.cs:155)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()
```

On line https://github.com/sebas77/Svelto.ECS/blob/master/com.sebaslab.svelto.ecs/Extensions/Unity/DOTS/UECS/SveltoOnDOTSEnginesGroup.cs#L72 in Svelto.ECS.

I'm using Unity 2023.1.7f1 instead of the 2023.1.0f1, but this error seems to be resulting from some facts that were known for quite some time already: https://forum.unity.com/threads/all-componenttype-must-be-known-at-compile-time.713900/ (circa 2019), so it should not be affecting this matter.

Note: This exception is not readily available to see, I had to explicitly search for why the example was silently just doing nothing, so I had to debug the code, and I put an explicit try-catch with debug output around that statement to catch the exception. Otherwise the exception is just silently ignored by Unity because it happens in another thread.

**Comment by sebas77** [comment]
Unity introduced a bug with the latest DOTS ECS version, but I fixed this demo with a workaround.
