### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by psygames** [sebas77/Svelto.MiniExamples#5]
compile error cause missing script 'UECSEntityComponent' .
in project [https://github.com/sebas77/Svelto.MiniExamples/tree/master/Example1-DOTS-DoofusesMustEat/DOOFUSES_UECS](https://github.com/sebas77/Svelto.MiniExamples/tree/master/Example1-DOTS-DoofusesMustEat/DOOFUSES_UECS)

error message: Assets\Code\DoofusEntityDescriptor.cs(6,60): error CS0246: The type or namespace name 'UECSEntityComponent' could not be found (are you missing a using directive or an assembly reference?)

aha, i fix it , new script named UECSEntityComponent, code is:
```
using Unity.Entities;
using Unity.Mathematics;

namespace Svelto.ECS.MiniExamples.Example1C
{
    public struct UECSEntityComponent : IEntityComponent
    {
        public Entity uecsEntity;
        public float3 spawnPosition;
    }
}

```

**Comment by sebas77** [comment]
thank you I will check this asap

**Comment by sebas77** [comment]
Fixed it, at last I did it :)
